import { Contact } from '../types.ts';

export const contacts: Contact[] = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    title: 'Software Engineer',
    avatarUrl: 'avatar-1.jpg',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    title: 'Product Manager',
    initialsColor: '#2A7E3B',
    backgroundColor: '#C9E8CA',
  },
  {
    id: 3,
    firstName: 'Mark',
    lastName: 'Brown',
    title: 'UI/UX Designer',
    avatarUrl: 'avatar-2.jpg',
  },
  {
    id: 4,
    firstName: 'Emily',
    lastName: 'Davis',
    title: 'Data Scientist',
    initialsColor: '#0D74CE',
    backgroundColor: '#C2E5FF',
  },
  {
    id: 5,
    firstName: 'James',
    lastName: 'Wilson',
    title: 'DevOps Engineer',
    avatarUrl: 'avatar-3.jpg',
  },
  {
    id: 6,
    firstName: 'Olivia',
    lastName: 'Martinez',
    title: 'Scrum Master',
    initialsColor: '#6550B9',
    backgroundColor: '#E1D9FF',
  },
  {
    id: 7,
    firstName: 'Daniel',
    lastName: 'Garcia',
    title: 'QA Engineer',
    avatarUrl: 'avatar-4.jpg',
  },
  {
    id: 8,
    firstName: 'Isabella',
    lastName: 'Rodriguez',
    title: 'Marketing Lead',
    initialsColor: '#CE2C31',
    backgroundColor: '#FFCDCE',
  },
  {
    id: 9,
    firstName: 'Matthew',
    lastName: 'Lee',
    title: 'Security Analyst',
    avatarUrl: 'avatar-5.jpg',
  },
  {
    id: 10,
    firstName: 'SophiaSophiaSophiaSophiaSophia',
    lastName: 'Walker',
    title: 'HR SpecialistSophiaSophiaSophiaSophiaSophiaSophiaSophia',
    initialsColor: '#CC4E00',
    backgroundColor: '#FFD19A',
  },
  {
    id: 11,
    firstName: 'Christopher',
    lastName: 'Hall',
    title: 'Cloud Architect',
    avatarUrl: 'avatar-6.jpg',
  },
  {
    id: 12,
    firstName: 'Ava',
    lastName: 'Allen',
    title: 'Business Analyst',
    initialsColor: '#5C7C2F',
    backgroundColor: '#D3E7A6',
  },
  {
    id: 13,
    firstName: 'Ethan',
    lastName: 'Young',
    title: 'Support Engineer',
    avatarUrl: 'avatar-7.jpg',
  },
  {
    id: 14,
    firstName: 'Mia',
    lastName: 'King',
    title: 'Finance Manager',

    initialsColor: '#CC4E00',
    backgroundColor: '#FFD19A',
  },
  {
    id: 15,
    firstName: 'Alexander',
    lastName: 'Wright',
    title: 'Legal Counsel',
    avatarUrl: 'avatar-8.jpg',
  },
];
