import { Contact } from '../types.ts';

export const contacts: Contact[] = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    title: 'Software Engineer',
    avatarUrl: 'avatar-1.jpg',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    title: 'Product Manager',
    initialsColor: '#FFFFFF',
    backgroundColor: '#FF5733',
  },
  {
    id: 3,
    firstName: 'Mark',
    lastName: 'Brown',
    title: 'UI/UX Designer',
    avatarUrl: 'avatar-2.jpg',
  },
  {
    id: 4,
    firstName: 'Emily',
    lastName: 'Davis',
    title: 'Data Scientist',
    initialsColor: '#000000',
    backgroundColor: '#C70039',
  },
  {
    id: 5,
    firstName: 'James',
    lastName: 'Wilson',
    title: 'DevOps Engineer',
    avatarUrl: 'avatar-3.jpg',
  },
  {
    id: 6,
    firstName: 'Olivia',
    lastName: 'Martinez',
    title: 'Scrum Master',
    initialsColor: '#34495E',
    backgroundColor: '#2980B9',
  },
  {
    id: 7,
    firstName: 'Daniel',
    lastName: 'Garcia',
    title: 'QA Engineer',
    avatarUrl: 'avatar-4.jpg',
  },
  {
    id: 8,
    firstName: 'Isabella',
    lastName: 'Rodriguez',
    title: 'Marketing Lead',
    initialsColor: '#E74C3C',
    backgroundColor: '#F39C12',
  },
  {
    id: 9,
    firstName: 'Matthew',
    lastName: 'Lee',
    title: 'Security Analyst',
    avatarUrl: 'avatar-5.jpg',
  },
  {
    id: 10,
    firstName: 'Sophia',
    lastName: 'Walker',
    title: 'HR Specialist',
    initialsColor: '#16A085',
    backgroundColor: '#2ECC71',
  },
  {
    id: 11,
    firstName: 'Christopher',
    lastName: 'Hall',
    title: 'Cloud Architect',
    avatarUrl: 'avatar-6.jpg',
  },
  {
    id: 12,
    firstName: 'Ava',
    lastName: 'Allen',
    title: 'Business Analyst',
    initialsColor: '#8E44AD',
    backgroundColor: '#9B59B6',
  },
  {
    id: 13,
    firstName: 'Ethan',
    lastName: 'Young',
    title: 'Support Engineer',
    avatarUrl: 'avatar-7.jpg',
  },
  {
    id: 14,
    firstName: 'Mia',
    lastName: 'King',
    title: 'Finance Manager',

    initialsColor: '#D35400',
    backgroundColor: '#E67E22',
  },
  {
    id: 15,
    firstName: 'Alexander',
    lastName: 'Wright',
    title: 'Legal Counsel',
    avatarUrl: 'avatar-8.jpg',
  },
];
